### ISSUE TITLE
Double primary key in setting table

### ISSUE THREAD

**Issue by welshjf** [GitGuild/sqlalchemy-models#8]
Via DeSW on Postgres:

```
IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(setting, 2200) already exists.
[SQL: '\nCREATE TABLE setting (\n\tid INTEGER NOT NULL, \n\tname VARCHAR(80) NOT NULL, \n\tdescription VARCHAR(320), \n\tvalue_type setting_value_type, \n\tPRIMARY KEY (id, name)\n)\n\n']
```

I'm guessing setting.name should be unique=True rather than primary_key=True. I haven't tried the ledger branch yet but it appears unchanged.

There are also some enums in need of names here as per https://github.com/GitGuild/desw/issues/22.

**Comment by isysd** [comment]
Postgres FTW. Nice and strict, to point out your faults. ;)
